baseurl = "https://crookm.com/"
title = "Matt Crook"

theme = "temple"
languageCode = "en-NZ"
#copyright = "(c) matt crook"

pygmentsStyle = "friendly"
pygmentsCodeFences = true

[params]
  topmenu = "categories" # enables topmenu
  #toc = true # table of contents

  dateformatpretty = "2006-01-02"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Matt Crook"
  github = "crookm"
  twitter = "mattlc_3"
  email = "mattlcrook@icloud.com"
  gaid = "UA-113693681-1"

[permalinks]
  posts = "/journal/:year/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200
